AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Schedule non stripe org donation by sending an sqs event to our lambda which will distribute donos
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
Resources:
  ScheduleManualOrgDonoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 240
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Events:
        EveryNight:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 15 * ? *)
      Policies:
        - AmazonSQSFullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
